#!/bin/sh

FLUTTER_VERSION="$1"

case "$FLUTTER_VERSION" in
     1.*) flutter analyze ;;
     2.*) flutter analyze --fatal-infos --fatal-warnings ;;
     *) echo "Unknown Flutter version ${FLUTTER_VERSION}" >&2 && exit 1 ;;
esac
